matrix:
- name: Markdown
  expect_match: false
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
      - 'img[alt]'
  sources:
  - 'docs/**/**/*.md'
  - 'docs/**/*.md'
  - 'docs/*.md'
