services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    dns_search: ''
    networks:
      - net
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs:cached

networks:
  net:
    driver: bridge
