"""Hook to inject recent blog posts into the homepage context.

Runs as an mkdocs hook (on_page_context) or as a standalone script for
builders like Zensical that have no hook support. Standalone, it renders
the same three posts into overrides/partials/recent-posts.html, which
home.html includes when no recent_posts context is present:

    python3 overrides/hooks/blog_posts.py
"""

import html
import os
import yaml
import datetime


def on_page_context(context, page, config, nav):
    """Inject recent blog posts into the homepage template context."""
    if page.file.src_path != "index.md":
        return context

    posts_dir = os.path.join(config["docs_dir"], "blog", "posts")
    context["recent_posts"] = _collect_posts(posts_dir)
    return context


def _collect_posts(posts_dir, limit=3):
    """Collect the latest posts from blog front matter, newest first."""
    if not os.path.isdir(posts_dir):
        return []

    posts = []
    for filename in os.listdir(posts_dir):
        if not filename.endswith(".md"):
            continue
        filepath = os.path.join(posts_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()

        # Parse front matter
        if not content.startswith("---"):
            continue
        end = content.index("---", 3)
        front_matter = yaml.safe_load(content[3:end])

        title = front_matter.get("title", "Untitled")
        post_date = front_matter.get("date")
        slug = front_matter.get("slug", filename.replace(".md", ""))

        # Normalize date to datetime.date
        if isinstance(post_date, str):
            post_date = datetime.datetime.strptime(post_date, "%Y-%m-%d").date()
        elif isinstance(post_date, datetime.datetime):
            post_date = post_date.date()
        elif isinstance(post_date, datetime.date):
            pass  # already a date
        else:
            continue

        # Build URL matching mkdocs-material blog plugin URL pattern
        date_path = post_date.strftime("%Y/%m/%d")
        url = f"blog/{date_path}/{slug}/"

        categories = front_matter.get("categories", [])

        posts.append({
            "title": title,
            "date": post_date,
            "date_formatted": post_date.strftime("%B %d, %Y"),
            "url": url,
            "category": categories[0] if categories else None,
        })

    # Sort by date descending, take the latest ones
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts[:limit]


def _render_partial(posts):
    """Render the Latest News section markup (mirrors home.html's loop)."""
    lines = [
        "<!-- Generated by overrides/hooks/blog_posts.py — do not edit. -->",
        '<section class="mdx-news">',
        '  <div class="md-grid md-typeset">',
        '    <h2 class="mdx-news__heading">Latest News</h2>',
        '    <div class="mdx-news__list">',
    ]
    for post in posts:
        lines.append(f'      <a href="{html.escape(post["url"])}" class="mdx-news__item">')
        lines.append(f'        <div class="mdx-news__date">{html.escape(post["date_formatted"])}</div>')
        lines.append(f'        <div class="mdx-news__title">{html.escape(post["title"])}</div>')
        if post["category"]:
            lines.append(f'        <span class="mdx-news__category">{html.escape(post["category"])}</span>')
        lines.append('      </a>')
    lines += [
        '    </div>',
        '    <div class="mdx-news__cta">',
        '      <a href="blog/">View all posts →</a>',
        '    </div>',
        '  </div>',
        '</section>',
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    _repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    _posts = _collect_posts(os.path.join(_repo_root, "docs", "blog", "posts"))
    _output_path = os.path.join(_repo_root, "overrides", "partials", "recent-posts.html")
    if _posts:
        with open(_output_path, "w", encoding="utf-8") as f:
            f.write(_render_partial(_posts))
        print(f"blog_posts: wrote {len(_posts)} posts to {_output_path}")
    else:
        print("blog_posts: no posts found, skipping")
