name: spellcheck
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install aspell
        run: sudo apt-get install -y aspell aspell-en
      - name: Install Python packages
        run: make install-python-packages
      - name: Check Spelling
        run: make spellcheck
